# @package _group_
_target_: src.solvers.MCMCSolver
beta: 1
step: 2000
start: empty # 'empty' or 'binom'
seed: null
scheduler:
  checkpoints: [500, 1000, 1500]
  betas: [5, 25, 125]
use_best: true
visualize: False
